<?php
/**
 * GBPrimePay_Payments extension
 * @package GBPrimePay_Payments
 * @copyright Copyright (c) 2020 GBPrimePay Payments (https://gbprimepay.com/)
 */
// @codingStandardsIgnoreFile
/**@var \GBPrimePay\Payments\Block\Customer\Card $block */

$delUrl = $block->getUrl('gbprimepay/customer/del');
?>
<script>
    window.delUrl = '<?php echo $delUrl; ?>';

</script>

<?php
/**
 */
$cards = $block->getDataCard();
?>

<table id="customer-booking-order-list" class="data table table-downloadable-products">
    <?php if (!sizeof($cards)) { ?>
        <div class="message info empty">
            <span><?php echo __('You don\'t store any card yet.'); ?></span>
        </div>
    <?php } else {
        $i = 0;
        ?>
        <thead>
        <tr>
            <th><?php echo __('ID'); ?></th>
            <th><?php echo __('Credit Card Name'); ?></th>
            <th><?php echo __('Created At'); ?></th>
            <th><?php echo __('Action'); ?></th>
        </tr>
        </thead>

        <tbody id="card_table_body">
        <?php foreach ($cards as $card) { ?>
            <tr id="row-<?php echo $card['id']; ?>">
                <td><?php echo ++$i; ?></td>
                <td><?php echo $card['credit_card_name']; ?></td>
                <td><?php echo $card['created_at']; ?></td>
                <td>
                    <button class="action primary" id="del-<?php echo $card['id']; ?>"
                            value="<?php echo $card['id']; ?>">
                        <span><?php echo __('Delete Card') ?></span>
                    </button>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    <?php } ?>
</table>
