<?php
/**
 * GBPrimePay_Payments extension
 * @package GBPrimePay_Payments
 * @copyright Copyright (c) 2020 GBPrimePay Payments (https://gbprimepay.com/)
 */
// @codingStandardsIgnoreFile
?>
<?php /** @var $block \Magento\Sales\Block\Adminhtml\Order\View\Tab\Info */ ?>
<?php $_order = $block->getOrder() ?>
<?php
$_payment = $_order->getPayment();
$checkFlag = false;
$gbpFlag = false;
if ($_payment->getAdditionalInformation('gbp_reference_no')) {
    $dataCode = $_payment->getAdditionalInformation();
    $checkFlag = false;
    $gbpFlag = true;
}else if ($_payment->getAdditionalInformation('transaction_id')) {
    $dataCode = $_payment->getAdditionalInformation();
    $checkFlag = true;
    $gbpFlag = false;
}
?>
<div id="order-messages">
    <?php echo $block->getChildHtml('order_messages') ?>
</div>
<?php echo $block->getChildHtml('order_info') ?>
<input type="hidden" name="order_id" value="<?php /* @escapeNotVerified */
echo $_order->getId() ?>"/>

<section class="admin__page-section order-view-billing-shipping">
    <div class="admin__page-section-title">
        <span class="title"><?php /* @escapeNotVerified */
            echo __('Payment &amp; Shipping Method') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-payment-method<?php if ($_order->getIsVirtual()): ?> order-payment-method-virtual<?php endif; ?>">
            <?php /* Payment Method */ ?>
            <div class="admin__page-section-item-title">
                <span class="title"><?php /* @escapeNotVerified */
                    echo __('Payment Information') ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <div class="order-payment-method-title"><?php echo $block->getPaymentHtml() ?></div>
                <div class="order-payment-currency"><?php /* @escapeNotVerified */
                    echo __('The order was placed using %1.', $_order->getOrderCurrencyCode()) ?></div>
                <div class="order-payment-additional">
                    <?php echo $block->getChildHtml('order_payment_additional'); ?>
                    <?php echo $block->getChildHtml('payment_additional_info'); ?>
                </div>
                <?php if ($checkFlag) : ?>
                    <div>
                        <table class="data-table admin__table-secondary">
                            <tbody>
                            <tr>
                                <th>Status:</th>
                                <td>
                                    <?php echo isset($dataCode['method_title']) ? 'Waiting for '.$dataCode['method_title'] : '' ?>
                                </td>
                            </tr>
                            <tr>
                                <th>Transaction ID:</th>
                                <td>
                                    <?php echo isset($dataCode['transaction_id']) ? $dataCode['transaction_id'] : '' ?>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                <?php endif; ?>
                
                <?php if ($gbpFlag) : ?>
                    <div>
                        <table class="data-table admin__table-secondary">
                            <tbody>
                            <tr>
                                <th>Status:</th>
                                <td>
                                    <?php echo isset($dataCode['method_title']) ? 'Payment Authorized, '.$dataCode['method_title'] : '' ?>
                                </td>
                            </tr>
                            <tr>
                                <th>Reference ID:</th>
                                <td>
                                    <?php echo isset($dataCode['gbp_reference_no']) ? $dataCode['gbp_reference_no'] : '' ?>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                <?php endif; ?>
            </div>
        </div>
        <?php echo $block->getChildHtml('order_shipping_view') ?>
    </div>
</section>
<?php echo $block->getGiftOptionsHtml() ?>
<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?php /* @escapeNotVerified */
            echo __('Items Ordered') ?></span>
    </div>
    <?php echo $block->getItemsHtml() ?>
</section>
<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?php /* @escapeNotVerified */
            echo __('Order Total') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-comments-history">
            <div class="admin__page-section-item-title">
                <span class="title"><?php /* @escapeNotVerified */
                    echo __('Notes for this Order') ?></span>
            </div>
            <?php echo $block->getChildHtml('order_history') ?>
        </div>
        <div class="admin__page-section-item order-totals">
            <div class="admin__page-section-item-title">
                <span class="title"><?php /* @escapeNotVerified */
                    echo __('Order Totals') ?></span>
            </div>
            <?php echo $block->getChildHtml('order_totals') ?>
        </div>
    </div>
</section>
<?php echo $block->getChildHtml('popup_window'); ?>
<script>
    require([
        "prototype",
        "Magento_Sales/order/giftoptions_tooltip"
    ], function () {
        /**
         * Retrieve gift options tooltip content
         */
        function getGiftOptionsTooltipContent(itemId) {
            var contentLines = [];
            var headerLine = null;
            var contentLine = null;

            $$('#gift_options_data_' + itemId + ' .gift-options-tooltip-content').each(function (element) {
                if (element.down(0)) {
                    headerLine = element.down(0).innerHTML;
                    contentLine = element.down(0).next().innerHTML;
                    if (contentLine.length > 30) {
                        contentLine = contentLine.slice(0, 30) + '...';
                    }
                    contentLines.push(headerLine + ' ' + contentLine);
                }
            });
            return contentLines.join('<br/>');
        }
        giftOptionsTooltip.setTooltipContentLoaderFunction(getGiftOptionsTooltipContent);
        window.getGiftOptionsTooltipContent = getGiftOptionsTooltipContent;
    });
</script>
